[package]
name = "vm_api"
version = "0.1.0"
authors = ["jose"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand="0.8"
actix-web="3"
serde="1.0"
serde_json="1.0"
regex="1.4"
btl = "0.2.8"